# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ZZULI Auto COVID Health Report

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 0,22,23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Working'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MOBILE: ${{ secrets.MOBILE }}
          HOMEMOBILE: ${{ secrets.HOMEMOBILE }}
          GPS: ${{ secrets.GPS }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
          NOTICETYPE: ${{ secrets.NOTICETYPE }}
          REGION: ${{ secrets.REGION }}
          AREA: ${{ secrets.AREA }}
          BUILD: ${{ secrets.BUILD }}
          DORM: ${{ secrets.DORM }}
          SCHOOLGPS: ${{ secrets.SCHOOLGPS }}
          SCHOOLLAT: ${{ secrets.SCHOOLLAT }}
          SCHOOLLON: ${{ secrets.SCHOOLLON }}
          USER: ${{ secrets.MYUSER }}
          SENDER: ${{ secrets.MYSENDER }}
          SMTPDOMAIN: ${{ secrets.SMTPDOMAIN }}
          SMTPAUTH: ${{ secrets.SMTPAUTH }}
          HOME: ${{ secrets.HOME }}
          VACCINE: ${{ secrets.VACCINE }}
          NUCLEICACIDTEST: ${{ secrets.NUCLEICACIDTEST }}
        run: |
          # sudo cp -p ./chrome/chromedriver /usr/bin/
          # chmod -R 777 /usr/bin/chromedriver
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && sudo echo "202.196.0.40 msg.zzuli.edu.cn" |sudo tee -a /etc/hosts && date && python run.py
         
